import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY is not set');
    }

    const { userImageBase64, productName, productDescription, productImageUrl } = await req.json();

    if (!userImageBase64 || !productName) {
      throw new Error('Missing required fields: userImageBase64 and productName are required');
    }

    console.log(`Processing virtual try-on for product: ${productName}`);

    // Build the messages for the AI
    const messages: any[] = [
      {
        role: "user",
        content: [
          {
            type: "text",
            text: `You are a virtual fashion try-on assistant. Take the person in this photo and generate a realistic image of them wearing the following clothing item:

Product: ${productName}
Description: ${productDescription || 'A stylish fashion item'}

Important instructions:
- Keep the person's face, body proportions, and pose exactly the same
- Replace or overlay their current top/clothing with the described item
- Make the clothing fit naturally on their body
- Maintain realistic lighting and shadows
- The result should look like a professional fashion photo
- Keep the background similar or slightly enhanced

Generate a high-quality, realistic image of this person wearing the described clothing item.`
          },
          {
            type: "image_url",
            image_url: {
              url: userImageBase64.startsWith('data:') ? userImageBase64 : `data:image/jpeg;base64,${userImageBase64}`
            }
          }
        ]
      }
    ];

    // If product image is provided, add it as reference
    if (productImageUrl) {
      messages[0].content.push({
        type: "text",
        text: "\n\nHere is the reference image of the clothing item to apply:"
      });
      messages[0].content.push({
        type: "image_url",
        image_url: {
          url: productImageUrl
        }
      });
    }

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image-preview",
        messages: messages,
        modalities: ["image", "text"]
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("AI API error:", errorText);
      throw new Error(`AI API error: ${response.status}`);
    }

    const data = await response.json();
    console.log("AI response received successfully");

    // Extract the generated image
    const generatedImage = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;
    const textResponse = data.choices?.[0]?.message?.content;

    if (!generatedImage) {
      throw new Error('No image was generated by the AI');
    }

    return new Response(
      JSON.stringify({ 
        success: true,
        image: generatedImage,
        message: textResponse || 'Virtual try-on generated successfully!'
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error: unknown) {
    console.error('Error in virtual-try-on function:', error);
    const errorMessage = error instanceof Error ? error.message : 'Failed to process virtual try-on';
    return new Response(
      JSON.stringify({ 
        success: false, 
        error: errorMessage
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500 
      }
    );
  }
});
